#!/bin/sh
#
# PROVIDE: webinterface
# REQUIRE: networking
# KEYWORD:

. /etc/rc.subr

name="webinterface"
rcvar="webinterface_enable"
goprogram_command="/usr/local/www/go.kroning.ru/www/services/webinterface/main"
pidfile="/var/run/${name}.pid"
command="/usr/sbin/daemon"
command_args="-P ${pidfile} -r -f ${goprogram_command}"

load_rc_config $name
: ${goprogram_enable:=no}

run_rc_command "$1"

