version: '3.8'

services:
  postgresql:
    image: postgres:15.1-alpine
    restart: always
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: shortner
      POSTGRES_PASSWORD: ZuSshortner098!
      POSTGRES_DB: postgres
    volumes:
      - /var/lib/postgresql/docker/data:/var/lib/postgresql/data
      - ./install/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  admin:
    image: admin1.1.3:multy
    container_name: admin
    depends_on: 
      - postgresql
    environment:
      DB_HOST: postgresql
    ports:
      - '9990:9990'

  redirect:
    image: redirect1.1.3:multy
    container_name: redirect
    depends_on: 
      - postgresql
    environment:
      DB_HOST: postgresql
    ports:
      - '9991:9991'

  nginx:
    image: nginx:1.23.3-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./docker/admin-nginx.conf:/etc/nginx/conf.d/admin-nginx.conf
      - ./docker/redirect-nginx.conf:/etc/nginx/conf.d/redirect-nginx.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"

