FROM golang:1.19.4-alpine AS build

WORKDIR /app

COPY . .

RUN go mod download

RUN go build -o ./cmd/main ./cmd/main.go

#Deploy
FROM alpine:3.17.0

WORKDIR /app

COPY --from=build /app/cmd/main ./cmd/main 
RUN mkdir logs
COPY --from=build /app/configs/ ./configs/
COPY --from=build /app/views/ ./views/
COPY --from=build /app/static ./static/

EXPOSE 9990

ENTRYPOINT ["./cmd/main", "-app", "admin"]
